"""Auto-generated API Test Suite
Generated by AITestFlow - AI-Driven Black-Box Testing Platform
Timestamp: 2026-04-13T19:59:00.634853
"""

import pytest
import requests
from typing import Dict, Any, Optional

BASE_URL = "http://localhost:8000"

def make_request(
    method: str,
    endpoint: str,
    params: Optional[Dict] = None,
    data: Optional[Dict] = None,
    headers: Optional[Dict] = None,
    expected_status: int = 200,
) -> requests.Response:
    """HTTP helper; expected_status is accepted so generated tests share one signature."""
    _ = expected_status
    url = f"{BASE_URL}{endpoint}"

    try:
        if method == "GET":
            return requests.get(url, params=params, headers=headers, timeout=10)
        elif method == "POST":
            return requests.post(url, json=data, params=params, headers=headers, timeout=10)
        elif method == "PUT":
            return requests.put(url, json=data, params=params, headers=headers, timeout=10)
        elif method == "DELETE":
            return requests.delete(url, params=params, headers=headers, timeout=10)
        elif method == "PATCH":
            return requests.patch(url, json=data, params=params, headers=headers, timeout=10)
        else:
            raise ValueError(f"Unsupported HTTP method: {method}")
    except requests.exceptions.RequestException as e:
        pytest.fail(f"Request failed: {str(e)}")

test_scenarios_1 = [
    {
        "test_id": "TC001",
        "endpoint": "/pets",
        "method": "GET",
        "query": {"limit": 50, "status": "available"},
        "payload": {},
        "expected_status": 200,
        "covered_condition_ids": ["limit_valid_1", "status_valid_1"]
    },
    {
        "test_id": "TC002",
        "endpoint": "/pets",
        "method": "GET",
        "query": {"limit": 25, "status": "pending"},
        "payload": {},
        "expected_status": 200,
        "covered_condition_ids": ["limit_valid_2", "status_valid_2"]
    },
    {
        "test_id": "TC003",
        "endpoint": "/pets",
        "method": "GET",
        "query": {"limit": 1, "status": "sold"},
        "payload": {},
        "expected_status": 200,
        "covered_condition_ids": ["limit_boundary_1", "status_valid_3"]
    },
    {
        "test_id": "TC004",
        "endpoint": "/pets",
        "method": "GET",
        "query": {"limit": 100},
        "payload": {},
        "expected_status": 200,
        "covered_condition_ids": ["limit_boundary_2"]
    },
    {
        "test_id": "TC_NEG_001",
        "endpoint": "/pets",
        "method": "GET",
        "query": {"limit": "ten"},
        "payload": {},
        "expected_status": 400,
        "covered_condition_ids": ["limit_invalid_type"]
    },
    {
        "test_id": "TC_NEG_002",
        "endpoint": "/pets",
        "method": "GET",
        "query": {"limit": 0},
        "payload": {},
        "expected_status": 400,
        "covered_condition_ids": ["limit_invalid_1", "limit_boundary_3"]
    },
    {
        "test_id": "TC_NEG_003",
        "endpoint": "/pets",
        "method": "GET",
        "query": {"limit": 101},
        "payload": {},
        "expected_status": 400,
        "covered_condition_ids": ["limit_invalid_2", "limit_boundary_4"]
    },
    {
        "test_id": "TC_NEG_004",
        "endpoint": "/pets",
        "method": "GET",
        "query": {"status": "adopted"},
        "payload": {},
        "expected_status": 400,
        "covered_condition_ids": ["status_invalid_1"]
    },
    {
        "test_id": "TC_NEG_005",
        "endpoint": "/pets",
        "method": "GET",
        "query": {"status": "Available"},
        "payload": {},
        "expected_status": 400,
        "covered_condition_ids": ["status_invalid_2"]
    },
    {
        "test_id": "TC_NEG_006",
        "endpoint": "/pets",
        "method": "GET",
        "query": {"status": 123},
        "payload": {},
        "expected_status": 400,
        "covered_condition_ids": ["status_invalid_type"]
    }
]

@pytest.mark.parametrize(
    "scenario",
    test_scenarios_1,
    ids=[s["test_id"] for s in test_scenarios_1]
)
def test_api_scenario_1(scenario):
    params = scenario.get("query", {})
    data = scenario.get("payload", {})
    response = make_request(
        method=scenario["method"],
        endpoint=scenario["endpoint"],
        params=params,
        data=data,
        expected_status=scenario["expected_status"]
    )
    assert response.status_code == scenario["expected_status"], f"Expected status {scenario['expected_status']}, got {response.status_code}. Response: {response.text}"
    if scenario["expected_status"] != 204:
        try:
            response.json()
        except ValueError:
            pytest.fail(f"Response is not valid JSON. Response text: {response.text}")

test_scenarios_2 = [
    {
        "test_id": "TC001",
        "endpoint": "/pets",
        "method": "POST",
        "query": {},
        "payload": {
            "name": "a",
            "status": "available",
            "category": "Dog",
            "price": 0
        },
        "expected_status": 201,
        "covered_condition_ids": [
            "name_valid_1",
            "status_valid_1",
            "category_valid_1",
            "price_valid_1"
        ]
    },
    {
        "test_id": "TC002",
        "endpoint": "/pets",
        "method": "POST",
        "query": {},
        "payload": {
            "name": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "status": "pending",
            "category": "",
            "price": 10000
        },
        "expected_status": 201,
        "covered_condition_ids": [
            "name_valid_2",
            "status_valid_2",
            "category_valid_2",
            "price_valid_2"
        ]
    },
    {
        "test_id": "TC003",
        "endpoint": "/pets",
        "method": "POST",
        "query": {},
        "payload": {
            "name": "Fluffy",
            "status": "sold",
            "category": "Dog",
            "price": 500.5
        },
        "expected_status": 201,
        "covered_condition_ids": [
            "name_valid_3",
            "status_valid_3",
            "category_valid_1",
            "price_valid_3"
        ]
    },
    {
        "test_id": "TC_BVA_001",
        "endpoint": "/pets",
        "method": "POST",
        "query": {},
        "payload": {
            "name": "",
            "status": "available",
            "category": "Dog",
            "price": 0
        },
        "expected_status": 400,
        "covered_condition_ids": [
            "name_boundary_1"
        ]
    },
    {
        "test_id": "TC_BVA_002",
        "endpoint": "/pets",
        "method": "POST",
        "query": {},
        "payload": {
            "name": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "status": "available",
            "category": "Dog",
            "price": 0
        },
        "expected_status": 400,
        "covered_condition_ids": [
            "name_boundary_2"
        ]
    },
    {
        "test_id": "TC_NEG_001",
        "endpoint": "/pets",
        "method": "POST",
        "query": {},
        "payload": {
            "name": 123,
            "status": "available",
            "category": "Dog",
            "price": 0
        },
        "expected_status": 400,
        "covered_condition_ids": [
            "name_invalid_type"
        ]
    },
    {
        "test_id": "TC_NEG_002",
        "endpoint": "/pets",
        "method": "POST",
        "query": {},
        "payload": {
            "name": "Fluffy",
            "status": "adopted",
            "category": "Dog",
            "price": 0
        },
        "expected_status": 400,
        "covered_condition_ids": [
            "status_invalid_1"
        ]
    },
    {
        "test_id": "TC_NEG_003",
        "endpoint": "/pets",
        "method": "POST",
        "query": {},
        "payload": {
            "name": "Fluffy",
            "status": True,
            "category": "Dog",
            "price": 0
        },
        "expected_status": 400,
        "covered_condition_ids": [
            "status_invalid_type"
        ]
    },
    {
        "test_id": "TC_NEG_004",
        "endpoint": "/pets",
        "method": "POST",
        "query": {},
        "payload": {
            "name": "Fluffy",
            "status": "available",
            "category": 42,
            "price": 0
        },
        "expected_status": 400,
        "covered_condition_ids": [
            "category_invalid_type"
        ]
    },
    {
        "test_id": "TC_BVA_003",
        "endpoint": "/pets",
        "method": "POST",
        "query": {},
        "payload": {
            "name": "Fluffy",
            "status": "available",
            "category": "Dog",
            "price": -1
        },
        "expected_status": 400,
        "covered_condition_ids": [
            "price_boundary_1"
        ]
    },
    {
        "test_id": "TC_BVA_004",
        "endpoint": "/pets",
        "method": "POST",
        "query": {},
        "payload": {
            "name": "Fluffy",
            "status": "available",
            "category": "Dog",
            "price": 10001
        },
        "expected_status": 400,
        "covered_condition_ids": [
            "price_boundary_2"
        ]
    },
    {
        "test_id": "TC_NEG_005",
        "endpoint": "/pets",
        "method": "POST",
        "query": {},
        "payload": {
            "name": "Fluffy",
            "status": "available",
            "category": "Dog",
            "price": "expensive"
        },
        "expected_status": 400,
        "covered_condition_ids": [
            "price_invalid_type"
        ]
    }
]

@pytest.mark.parametrize(
    "scenario",
    test_scenarios_2,
    ids=[s["test_id"] for s in test_scenarios_2]
)
def test_scenario(scenario):
    response = make_request(
        method=scenario["method"],
        endpoint=scenario["endpoint"],
        params=scenario["query"],
        data=scenario["payload"],
        expected_status=scenario["expected_status"]
    )
    assert response.status_code == scenario["expected_status"], f"Expected status {scenario['expected_status']}, got {response.status_code}. Response: {response.text}"
    if scenario["expected_status"] != 204:
        try:
            response.json()
        except ValueError:
            pytest.fail(f"Response body is not valid JSON. Response: {response.text}")

test_scenarios_3 = [
    {
        "test_id": "TC001",
        "endpoint": "/pets/5",
        "method": "GET",
        "query": {},
        "payload": {},
        "expected_status": 200,
        "covered_condition_ids": ["petId_valid_1"]
    },
    {
        "test_id": "TC002",
        "endpoint": "/pets/100",
        "method": "GET",
        "query": {},
        "payload": {},
        "expected_status": 200,
        "covered_condition_ids": ["petId_valid_2"]
    },
    {
        "test_id": "TC_BVA_001",
        "endpoint": "/pets/1",
        "method": "GET",
        "query": {},
        "payload": {},
        "expected_status": 200,
        "covered_condition_ids": ["petId_boundary_1"]
    },
    {
        "test_id": "TC_BVA_002",
        "endpoint": "/pets/0",
        "method": "GET",
        "query": {},
        "payload": {},
        "expected_status": 400,
        "covered_condition_ids": ["petId_boundary_2"]
    },
    {
        "test_id": "TC_NEG_001",
        "endpoint": "/pets/abc",
        "method": "GET",
        "query": {},
        "payload": {},
        "expected_status": 400,
        "covered_condition_ids": ["petId_invalid_type_string"]
    },
    {
        "test_id": "TC_NEG_002",
        "endpoint": "/pets/3.14",
        "method": "GET",
        "query": {},
        "payload": {},
        "expected_status": 400,
        "covered_condition_ids": ["petId_invalid_type_float"]
    },
    {
        "test_id": "TC_NEG_003",
        "endpoint": "/pets/-5",
        "method": "GET",
        "query": {},
        "payload": {},
        "expected_status": 400,
        "covered_condition_ids": ["petId_invalid_negative"]
    }
]

@pytest.mark.parametrize("scenario", test_scenarios_3, ids=[s["test_id"] for s in test_scenarios_3])
def test_api_scenario_3(scenario):
    response = make_request(
        method=scenario["method"],
        endpoint=scenario["endpoint"],
        params=scenario["query"],
        data=scenario["payload"],
        expected_status=scenario["expected_status"]
    )
    assert response.status_code == scenario["expected_status"], f"Expected status {scenario['expected_status']}, got {response.status_code}. Response: {response.text}"
    if scenario["expected_status"] != 204:
        try:
            response.json()
        except ValueError:
            pytest.fail(f"Response body is not valid JSON. Response: {response.text}")

test_scenarios_4 = [
    {
        "test_id": "TC001",
        "endpoint": "/pets/100",
        "method": "DELETE",
        "query": {},
        "payload": {},
        "expected_status": 204,
        "covered_condition_ids": ["petId_valid_1"]
    },
    {
        "test_id": "TC002",
        "endpoint": "/pets/1",
        "method": "DELETE",
        "query": {},
        "payload": {},
        "expected_status": 204,
        "covered_condition_ids": ["petId_valid_2", "petId_boundary_2"]
    },
    {
        "test_id": "TC_BVA_001",
        "endpoint": "/pets/0",
        "method": "DELETE",
        "query": {},
        "payload": {},
        "expected_status": 400,
        "covered_condition_ids": ["petId_boundary_1", "petId_invalid_2"]
    },
    {
        "test_id": "TC_INV_001",
        "endpoint": "/pets/abc",
        "method": "DELETE",
        "query": {},
        "payload": {},
        "expected_status": 400,
        "covered_condition_ids": ["petId_invalid_type_1"]
    },
    {
        "test_id": "TC_INV_002",
        "endpoint": "/pets/1.5",
        "method": "DELETE",
        "query": {},
        "payload": {},
        "expected_status": 400,
        "covered_condition_ids": ["petId_invalid_type_2"]
    },
    {
        "test_id": "TC_INV_003",
        "endpoint": "/pets/-10",
        "method": "DELETE",
        "query": {},
        "payload": {},
        "expected_status": 400,
        "covered_condition_ids": ["petId_invalid_1"]
    }
]

@pytest.mark.parametrize(
    "scenario",
    test_scenarios_4,
    ids=[s["test_id"] for s in test_scenarios_4]
)
def test_api_scenario_4(scenario):
    response = make_request(
        method=scenario["method"],
        endpoint=scenario["endpoint"],
        params=scenario["query"],
        data=scenario["payload"],
        expected_status=scenario["expected_status"]
    )
    assert response.status_code == scenario["expected_status"], f"Expected status {scenario['expected_status']}, got {response.status_code}. Response: {response.text}"
    if scenario["expected_status"] != 204:
        try:
            response.json()
        except Exception as e:
            pytest.fail(f"Failed to parse JSON response: {e}. Response text: {response.text}")

test_scenarios_5 = [
    {
        "test_id": "TC001",
        "endpoint": "/pets/100/vaccinations",
        "method": "POST",
        "query": {},
        "payload": {
            "vaccine_name": "Rabies Vaccine",
            "date": "2024-01-15"
        },
        "expected_status": 201,
        "covered_condition_ids": [
            "petid_valid_1",
            "vaccine_name_valid_1",
            "date_valid_1"
        ]
    },
    {
        "test_id": "TC002",
        "endpoint": "/pets/1/vaccinations",
        "method": "POST",
        "query": {},
        "payload": {
            "vaccine_name": "A",
            "date": "2024-01-15"
        },
        "expected_status": 201,
        "covered_condition_ids": [
            "petid_boundary_1",
            "vaccine_name_valid_2",
            "date_valid_1"
        ]
    },
    {
        "test_id": "TC_NEG_001",
        "endpoint": "/pets/0/vaccinations",
        "method": "POST",
        "query": {},
        "payload": {
            "vaccine_name": "Rabies Vaccine",
            "date": "2024-01-15"
        },
        "expected_status": 400,
        "covered_condition_ids": [
            "petid_boundary_2"
        ]
    },
    {
        "test_id": "TC_NEG_002",
        "endpoint": "/pets/abc/vaccinations",
        "method": "POST",
        "query": {},
        "payload": {
            "vaccine_name": "Rabies Vaccine",
            "date": "2024-01-15"
        },
        "expected_status": 400,
        "covered_condition_ids": [
            "petid_invalid_type_1"
        ]
    },
    {
        "test_id": "TC_NEG_003",
        "endpoint": "/pets/100/vaccinations",
        "method": "POST",
        "query": {},
        "payload": {
            "vaccine_name": 123,
            "date": "2024-01-15"
        },
        "expected_status": 400,
        "covered_condition_ids": [
            "vaccine_name_invalid_type_1"
        ]
    },
    {
        "test_id": "TC_NEG_004",
        "endpoint": "/pets/100/vaccinations",
        "method": "POST",
        "query": {},
        "payload": {
            "vaccine_name": "Rabies Vaccine",
            "date": "15/01/2024"
        },
        "expected_status": 400,
        "covered_condition_ids": [
            "date_invalid_format_1"
        ]
    },
    {
        "test_id": "TC_NEG_005",
        "endpoint": "/pets/100/vaccinations",
        "method": "POST",
        "query": {},
        "payload": {
            "vaccine_name": "Rabies Vaccine",
            "date": "2024-02-30"
        },
        "expected_status": 400,
        "covered_condition_ids": [
            "date_invalid_format_2"
        ]
    },
    {
        "test_id": "TC_NEG_006",
        "endpoint": "/pets/100/vaccinations",
        "method": "POST",
        "query": {},
        "payload": {
            "vaccine_name": "Rabies Vaccine",
            "date": 20240115
        },
        "expected_status": 400,
        "covered_condition_ids": [
            "date_invalid_type_1"
        ]
    }
]

@pytest.mark.parametrize(
    "scenario",
    test_scenarios_5,
    ids=[s["test_id"] for s in test_scenarios_5]
)
def test_api_scenario_5(scenario):
    response = make_request(
        method=scenario["method"],
        endpoint=scenario["endpoint"],
        params=scenario["query"],
        data=scenario["payload"],
        expected_status=scenario["expected_status"]
    )
    assert response.status_code == scenario["expected_status"], f"Expected status {scenario['expected_status']}, got {response.status_code}. Response: {response.text}"
    if scenario["expected_status"] != 204:
        try:
            response.json()
        except Exception as e:
            pytest.fail(f"Failed to parse JSON response: {e}. Response text: {response.text}")
